INSERT INTO order_numbers_dictionary__01 SELECT * FROM order_numbers_dictionary;
INSERT INTO order_numbers_dictionary__02 SELECT * FROM order_numbers_dictionary;
INSERT INTO order_numbers_dictionary__03 SELECT * FROM order_numbers_dictionary;
INSERT INTO order_numbers_dictionary__04 SELECT * FROM order_numbers_dictionary;
INSERT INTO order_numbers_dictionary__05 SELECT * FROM order_numbers_dictionary;
INSERT INTO order_numbers_dictionary__06 SELECT * FROM order_numbers_dictionary;
INSERT INTO order_numbers_dictionary__07 SELECT * FROM order_numbers_dictionary;
INSERT INTO order_numbers_dictionary__08 SELECT * FROM order_numbers_dictionary;
INSERT INTO order_numbers_dictionary__09 SELECT * FROM order_numbers_dictionary;
INSERT INTO sales__01 SELECT * FROM sales;
INSERT INTO sales__02 SELECT * FROM sales;
INSERT INTO sales__03 SELECT * FROM sales;
INSERT INTO sales__04 SELECT * FROM sales;
INSERT INTO sales__05 SELECT * FROM sales;
INSERT INTO sales__06 SELECT * FROM sales;
INSERT INTO sales__07 SELECT * FROM sales;
INSERT INTO sales__08 SELECT * FROM sales;
INSERT INTO sales__09 SELECT * FROM sales;

INSERT INTO order_numbers_dictionary__02(order_number, region_id, market_id, terminal_id, terminal_basket_number, basket_price, order_time, order_date, comment) (SELECT order_number+100000, region_id, market_id, terminal_id, terminal_basket_number, basket_price, order_time, order_date, comment FROM order_numbers_dictionary);
INSERT INTO order_numbers_dictionary__03(order_number, region_id, market_id, terminal_id, terminal_basket_number, basket_price, order_time, order_date, comment) (SELECT order_number+100000, region_id, market_id, terminal_id, terminal_basket_number, basket_price, order_time, order_date, comment FROM order_numbers_dictionary);
INSERT INTO order_numbers_dictionary__04(order_number, region_id, market_id, terminal_id, terminal_basket_number, basket_price, order_time, order_date, comment) (SELECT order_number+100000, region_id, market_id, terminal_id, terminal_basket_number, basket_price, order_time, order_date, comment FROM order_numbers_dictionary);
INSERT INTO order_numbers_dictionary__05(order_number, region_id, market_id, terminal_id, terminal_basket_number, basket_price, order_time, order_date, comment) (SELECT order_number+100000, region_id, market_id, terminal_id, terminal_basket_number, basket_price, order_time, order_date, comment FROM order_numbers_dictionary);
INSERT INTO order_numbers_dictionary__06(order_number, region_id, market_id, terminal_id, terminal_basket_number, basket_price, order_time, order_date, comment) (SELECT order_number+100000, region_id, market_id, terminal_id, terminal_basket_number, basket_price, order_time, order_date, comment FROM order_numbers_dictionary);
INSERT INTO order_numbers_dictionary__07(order_number, region_id, market_id, terminal_id, terminal_basket_number, basket_price, order_time, order_date, comment) (SELECT order_number+100000, region_id, market_id, terminal_id, terminal_basket_number, basket_price, order_time, order_date, comment FROM order_numbers_dictionary);
INSERT INTO order_numbers_dictionary__08(order_number, region_id, market_id, terminal_id, terminal_basket_number, basket_price, order_time, order_date, comment) (SELECT order_number+100000, region_id, market_id, terminal_id, terminal_basket_number, basket_price, order_time, order_date, comment FROM order_numbers_dictionary);
INSERT INTO order_numbers_dictionary__09(order_number, region_id, market_id, terminal_id, terminal_basket_number, basket_price, order_time, order_date, comment) (SELECT order_number+100000, region_id, market_id, terminal_id, terminal_basket_number, basket_price, order_time, order_date, comment FROM order_numbers_dictionary);
INSERT INTO sales__02(id, order_number, line_number_in_order, region_id, market_id, terminal_id, product_id, count_of_product, price_of_one_piece, order_date, client_id, comment) (SELECT id+1000000, order_number+100000, line_number_in_order, region_id, market_id, terminal_id, product_id, count_of_product, price_of_one_piece, order_date, client_id, comment FROM sales);
INSERT INTO sales__03(id, order_number, line_number_in_order, region_id, market_id, terminal_id, product_id, count_of_product, price_of_one_piece, order_date, client_id, comment) (SELECT id+1000000, order_number+100000, line_number_in_order, region_id, market_id, terminal_id, product_id, count_of_product, price_of_one_piece, order_date, client_id, comment FROM sales);
INSERT INTO sales__04(id, order_number, line_number_in_order, region_id, market_id, terminal_id, product_id, count_of_product, price_of_one_piece, order_date, client_id, comment) (SELECT id+1000000, order_number+100000, line_number_in_order, region_id, market_id, terminal_id, product_id, count_of_product, price_of_one_piece, order_date, client_id, comment FROM sales);
INSERT INTO sales__05(id, order_number, line_number_in_order, region_id, market_id, terminal_id, product_id, count_of_product, price_of_one_piece, order_date, client_id, comment) (SELECT id+1000000, order_number+100000, line_number_in_order, region_id, market_id, terminal_id, product_id, count_of_product, price_of_one_piece, order_date, client_id, comment FROM sales);
INSERT INTO sales__06(id, order_number, line_number_in_order, region_id, market_id, terminal_id, product_id, count_of_product, price_of_one_piece, order_date, client_id, comment) (SELECT id+1000000, order_number+100000, line_number_in_order, region_id, market_id, terminal_id, product_id, count_of_product, price_of_one_piece, order_date, client_id, comment FROM sales);
INSERT INTO sales__07(id, order_number, line_number_in_order, region_id, market_id, terminal_id, product_id, count_of_product, price_of_one_piece, order_date, client_id, comment) (SELECT id+1000000, order_number+100000, line_number_in_order, region_id, market_id, terminal_id, product_id, count_of_product, price_of_one_piece, order_date, client_id, comment FROM sales);
INSERT INTO sales__08(id, order_number, line_number_in_order, region_id, market_id, terminal_id, product_id, count_of_product, price_of_one_piece, order_date, client_id, comment) (SELECT id+1000000, order_number+100000, line_number_in_order, region_id, market_id, terminal_id, product_id, count_of_product, price_of_one_piece, order_date, client_id, comment FROM sales);
INSERT INTO sales__09(id, order_number, line_number_in_order, region_id, market_id, terminal_id, product_id, count_of_product, price_of_one_piece, order_date, client_id, comment) (SELECT id+1000000, order_number+100000, line_number_in_order, region_id, market_id, terminal_id, product_id, count_of_product, price_of_one_piece, order_date, client_id, comment FROM sales);


INSERT INTO order_numbers_dictionary__03(order_number, region_id, market_id, terminal_id, terminal_basket_number, basket_price, order_time, order_date, comment) (SELECT order_number+200000, region_id, market_id, terminal_id, terminal_basket_number, basket_price, order_time, order_date, comment FROM order_numbers_dictionary);
INSERT INTO order_numbers_dictionary__04(order_number, region_id, market_id, terminal_id, terminal_basket_number, basket_price, order_time, order_date, comment) (SELECT order_number+200000, region_id, market_id, terminal_id, terminal_basket_number, basket_price, order_time, order_date, comment FROM order_numbers_dictionary);
INSERT INTO order_numbers_dictionary__05(order_number, region_id, market_id, terminal_id, terminal_basket_number, basket_price, order_time, order_date, comment) (SELECT order_number+200000, region_id, market_id, terminal_id, terminal_basket_number, basket_price, order_time, order_date, comment FROM order_numbers_dictionary);
INSERT INTO order_numbers_dictionary__06(order_number, region_id, market_id, terminal_id, terminal_basket_number, basket_price, order_time, order_date, comment) (SELECT order_number+200000, region_id, market_id, terminal_id, terminal_basket_number, basket_price, order_time, order_date, comment FROM order_numbers_dictionary);
INSERT INTO order_numbers_dictionary__07(order_number, region_id, market_id, terminal_id, terminal_basket_number, basket_price, order_time, order_date, comment) (SELECT order_number+200000, region_id, market_id, terminal_id, terminal_basket_number, basket_price, order_time, order_date, comment FROM order_numbers_dictionary);
INSERT INTO order_numbers_dictionary__08(order_number, region_id, market_id, terminal_id, terminal_basket_number, basket_price, order_time, order_date, comment) (SELECT order_number+200000, region_id, market_id, terminal_id, terminal_basket_number, basket_price, order_time, order_date, comment FROM order_numbers_dictionary);
INSERT INTO order_numbers_dictionary__09(order_number, region_id, market_id, terminal_id, terminal_basket_number, basket_price, order_time, order_date, comment) (SELECT order_number+200000, region_id, market_id, terminal_id, terminal_basket_number, basket_price, order_time, order_date, comment FROM order_numbers_dictionary);
INSERT INTO sales__03(id, order_number, line_number_in_order, region_id, market_id, terminal_id, product_id, count_of_product, price_of_one_piece, order_date, client_id, comment) (SELECT id+2000000, order_number+200000, line_number_in_order, region_id, market_id, terminal_id, product_id, count_of_product, price_of_one_piece, order_date, client_id, comment FROM sales);
INSERT INTO sales__04(id, order_number, line_number_in_order, region_id, market_id, terminal_id, product_id, count_of_product, price_of_one_piece, order_date, client_id, comment) (SELECT id+2000000, order_number+200000, line_number_in_order, region_id, market_id, terminal_id, product_id, count_of_product, price_of_one_piece, order_date, client_id, comment FROM sales);
INSERT INTO sales__05(id, order_number, line_number_in_order, region_id, market_id, terminal_id, product_id, count_of_product, price_of_one_piece, order_date, client_id, comment) (SELECT id+2000000, order_number+200000, line_number_in_order, region_id, market_id, terminal_id, product_id, count_of_product, price_of_one_piece, order_date, client_id, comment FROM sales);
INSERT INTO sales__06(id, order_number, line_number_in_order, region_id, market_id, terminal_id, product_id, count_of_product, price_of_one_piece, order_date, client_id, comment) (SELECT id+2000000, order_number+200000, line_number_in_order, region_id, market_id, terminal_id, product_id, count_of_product, price_of_one_piece, order_date, client_id, comment FROM sales);
INSERT INTO sales__07(id, order_number, line_number_in_order, region_id, market_id, terminal_id, product_id, count_of_product, price_of_one_piece, order_date, client_id, comment) (SELECT id+2000000, order_number+200000, line_number_in_order, region_id, market_id, terminal_id, product_id, count_of_product, price_of_one_piece, order_date, client_id, comment FROM sales);
INSERT INTO sales__08(id, order_number, line_number_in_order, region_id, market_id, terminal_id, product_id, count_of_product, price_of_one_piece, order_date, client_id, comment) (SELECT id+2000000, order_number+200000, line_number_in_order, region_id, market_id, terminal_id, product_id, count_of_product, price_of_one_piece, order_date, client_id, comment FROM sales);
INSERT INTO sales__09(id, order_number, line_number_in_order, region_id, market_id, terminal_id, product_id, count_of_product, price_of_one_piece, order_date, client_id, comment) (SELECT id+2000000, order_number+200000, line_number_in_order, region_id, market_id, terminal_id, product_id, count_of_product, price_of_one_piece, order_date, client_id, comment FROM sales);

INSERT INTO order_numbers_dictionary__04(order_number, region_id, market_id, terminal_id, terminal_basket_number, basket_price, order_time, order_date, comment) (SELECT order_number+300000, region_id, market_id, terminal_id, terminal_basket_number, basket_price, order_time, order_date, comment FROM order_numbers_dictionary);
INSERT INTO order_numbers_dictionary__05(order_number, region_id, market_id, terminal_id, terminal_basket_number, basket_price, order_time, order_date, comment) (SELECT order_number+300000, region_id, market_id, terminal_id, terminal_basket_number, basket_price, order_time, order_date, comment FROM order_numbers_dictionary);
INSERT INTO order_numbers_dictionary__06(order_number, region_id, market_id, terminal_id, terminal_basket_number, basket_price, order_time, order_date, comment) (SELECT order_number+300000, region_id, market_id, terminal_id, terminal_basket_number, basket_price, order_time, order_date, comment FROM order_numbers_dictionary);
INSERT INTO order_numbers_dictionary__07(order_number, region_id, market_id, terminal_id, terminal_basket_number, basket_price, order_time, order_date, comment) (SELECT order_number+300000, region_id, market_id, terminal_id, terminal_basket_number, basket_price, order_time, order_date, comment FROM order_numbers_dictionary);
INSERT INTO order_numbers_dictionary__08(order_number, region_id, market_id, terminal_id, terminal_basket_number, basket_price, order_time, order_date, comment) (SELECT order_number+300000, region_id, market_id, terminal_id, terminal_basket_number, basket_price, order_time, order_date, comment FROM order_numbers_dictionary);
INSERT INTO order_numbers_dictionary__09(order_number, region_id, market_id, terminal_id, terminal_basket_number, basket_price, order_time, order_date, comment) (SELECT order_number+300000, region_id, market_id, terminal_id, terminal_basket_number, basket_price, order_time, order_date, comment FROM order_numbers_dictionary);
INSERT INTO sales__04(id, order_number, line_number_in_order, region_id, market_id, terminal_id, product_id, count_of_product, price_of_one_piece, order_date, client_id, comment) (SELECT id+3000000, order_number+300000, line_number_in_order, region_id, market_id, terminal_id, product_id, count_of_product, price_of_one_piece, order_date, client_id, comment FROM sales);
INSERT INTO sales__05(id, order_number, line_number_in_order, region_id, market_id, terminal_id, product_id, count_of_product, price_of_one_piece, order_date, client_id, comment) (SELECT id+3000000, order_number+300000, line_number_in_order, region_id, market_id, terminal_id, product_id, count_of_product, price_of_one_piece, order_date, client_id, comment FROM sales);
INSERT INTO sales__06(id, order_number, line_number_in_order, region_id, market_id, terminal_id, product_id, count_of_product, price_of_one_piece, order_date, client_id, comment) (SELECT id+3000000, order_number+300000, line_number_in_order, region_id, market_id, terminal_id, product_id, count_of_product, price_of_one_piece, order_date, client_id, comment FROM sales);
INSERT INTO sales__07(id, order_number, line_number_in_order, region_id, market_id, terminal_id, product_id, count_of_product, price_of_one_piece, order_date, client_id, comment) (SELECT id+3000000, order_number+300000, line_number_in_order, region_id, market_id, terminal_id, product_id, count_of_product, price_of_one_piece, order_date, client_id, comment FROM sales);
INSERT INTO sales__08(id, order_number, line_number_in_order, region_id, market_id, terminal_id, product_id, count_of_product, price_of_one_piece, order_date, client_id, comment) (SELECT id+3000000, order_number+300000, line_number_in_order, region_id, market_id, terminal_id, product_id, count_of_product, price_of_one_piece, order_date, client_id, comment FROM sales);
INSERT INTO sales__09(id, order_number, line_number_in_order, region_id, market_id, terminal_id, product_id, count_of_product, price_of_one_piece, order_date, client_id, comment) (SELECT id+3000000, order_number+300000, line_number_in_order, region_id, market_id, terminal_id, product_id, count_of_product, price_of_one_piece, order_date, client_id, comment FROM sales);

INSERT INTO order_numbers_dictionary__05(order_number, region_id, market_id, terminal_id, terminal_basket_number, basket_price, order_time, order_date, comment) (SELECT order_number+400000, region_id, market_id, terminal_id, terminal_basket_number, basket_price, order_time, order_date, comment FROM order_numbers_dictionary);
INSERT INTO order_numbers_dictionary__06(order_number, region_id, market_id, terminal_id, terminal_basket_number, basket_price, order_time, order_date, comment) (SELECT order_number+400000, region_id, market_id, terminal_id, terminal_basket_number, basket_price, order_time, order_date, comment FROM order_numbers_dictionary);
INSERT INTO order_numbers_dictionary__07(order_number, region_id, market_id, terminal_id, terminal_basket_number, basket_price, order_time, order_date, comment) (SELECT order_number+400000, region_id, market_id, terminal_id, terminal_basket_number, basket_price, order_time, order_date, comment FROM order_numbers_dictionary);
INSERT INTO order_numbers_dictionary__08(order_number, region_id, market_id, terminal_id, terminal_basket_number, basket_price, order_time, order_date, comment) (SELECT order_number+400000, region_id, market_id, terminal_id, terminal_basket_number, basket_price, order_time, order_date, comment FROM order_numbers_dictionary);
INSERT INTO order_numbers_dictionary__09(order_number, region_id, market_id, terminal_id, terminal_basket_number, basket_price, order_time, order_date, comment) (SELECT order_number+400000, region_id, market_id, terminal_id, terminal_basket_number, basket_price, order_time, order_date, comment FROM order_numbers_dictionary);
INSERT INTO sales__05(id, order_number, line_number_in_order, region_id, market_id, terminal_id, product_id, count_of_product, price_of_one_piece, order_date, client_id, comment) (SELECT id+4000000, order_number+400000, line_number_in_order, region_id, market_id, terminal_id, product_id, count_of_product, price_of_one_piece, order_date, client_id, comment FROM sales);
INSERT INTO sales__06(id, order_number, line_number_in_order, region_id, market_id, terminal_id, product_id, count_of_product, price_of_one_piece, order_date, client_id, comment) (SELECT id+4000000, order_number+400000, line_number_in_order, region_id, market_id, terminal_id, product_id, count_of_product, price_of_one_piece, order_date, client_id, comment FROM sales);
INSERT INTO sales__07(id, order_number, line_number_in_order, region_id, market_id, terminal_id, product_id, count_of_product, price_of_one_piece, order_date, client_id, comment) (SELECT id+4000000, order_number+400000, line_number_in_order, region_id, market_id, terminal_id, product_id, count_of_product, price_of_one_piece, order_date, client_id, comment FROM sales);
INSERT INTO sales__08(id, order_number, line_number_in_order, region_id, market_id, terminal_id, product_id, count_of_product, price_of_one_piece, order_date, client_id, comment) (SELECT id+4000000, order_number+400000, line_number_in_order, region_id, market_id, terminal_id, product_id, count_of_product, price_of_one_piece, order_date, client_id, comment FROM sales);
INSERT INTO sales__09(id, order_number, line_number_in_order, region_id, market_id, terminal_id, product_id, count_of_product, price_of_one_piece, order_date, client_id, comment) (SELECT id+4000000, order_number+400000, line_number_in_order, region_id, market_id, terminal_id, product_id, count_of_product, price_of_one_piece, order_date, client_id, comment FROM sales);

INSERT INTO order_numbers_dictionary__06(order_number, region_id, market_id, terminal_id, terminal_basket_number, basket_price, order_time, order_date, comment) (SELECT order_number+500000, region_id, market_id, terminal_id, terminal_basket_number, basket_price, order_time, order_date, comment FROM order_numbers_dictionary__01);
INSERT INTO order_numbers_dictionary__07(order_number, region_id, market_id, terminal_id, terminal_basket_number, basket_price, order_time, order_date, comment) (SELECT order_number+500000, region_id, market_id, terminal_id, terminal_basket_number, basket_price, order_time, order_date, comment FROM order_numbers_dictionary__02);
INSERT INTO order_numbers_dictionary__08(order_number, region_id, market_id, terminal_id, terminal_basket_number, basket_price, order_time, order_date, comment) (SELECT order_number+500000, region_id, market_id, terminal_id, terminal_basket_number, basket_price, order_time, order_date, comment FROM order_numbers_dictionary__03);
INSERT INTO order_numbers_dictionary__09(order_number, region_id, market_id, terminal_id, terminal_basket_number, basket_price, order_time, order_date, comment) (SELECT order_number+500000, region_id, market_id, terminal_id, terminal_basket_number, basket_price, order_time, order_date, comment FROM order_numbers_dictionary__04);
INSERT INTO sales__06(id, order_number, line_number_in_order, region_id, market_id, terminal_id, product_id, count_of_product, price_of_one_piece, order_date, client_id, comment) (SELECT id+5000000, order_number+500000, line_number_in_order, region_id, market_id, terminal_id, product_id, count_of_product, price_of_one_piece, order_date, client_id, comment FROM sales__01);
INSERT INTO sales__07(id, order_number, line_number_in_order, region_id, market_id, terminal_id, product_id, count_of_product, price_of_one_piece, order_date, client_id, comment) (SELECT id+5000000, order_number+500000, line_number_in_order, region_id, market_id, terminal_id, product_id, count_of_product, price_of_one_piece, order_date, client_id, comment FROM sales__02);
INSERT INTO sales__08(id, order_number, line_number_in_order, region_id, market_id, terminal_id, product_id, count_of_product, price_of_one_piece, order_date, client_id, comment) (SELECT id+5000000, order_number+500000, line_number_in_order, region_id, market_id, terminal_id, product_id, count_of_product, price_of_one_piece, order_date, client_id, comment FROM sales__03);
INSERT INTO sales__09(id, order_number, line_number_in_order, region_id, market_id, terminal_id, product_id, count_of_product, price_of_one_piece, order_date, client_id, comment) (SELECT id+5000000, order_number+500000, line_number_in_order, region_id, market_id, terminal_id, product_id, count_of_product, price_of_one_piece, order_date, client_id, comment FROM sales__04);


INSERT INTO order_numbers_dictionary__10(order_number, region_id, market_id, terminal_id, terminal_basket_number, basket_price, order_time, order_date, comment) (SELECT order_number, region_id, market_id, terminal_id, terminal_basket_number, basket_price, order_time, order_date, comment FROM order_numbers_dictionary__05);
INSERT INTO order_numbers_dictionary__10(order_number, region_id, market_id, terminal_id, terminal_basket_number, basket_price, order_time, order_date, comment) (SELECT order_number+500000, region_id, market_id, terminal_id, terminal_basket_number, basket_price, order_time, order_date, comment FROM order_numbers_dictionary__05);
INSERT INTO sales__10(id, order_number, line_number_in_order, region_id, market_id, terminal_id, product_id, count_of_product, price_of_one_piece, order_date, client_id, comment) (SELECT id, order_number, line_number_in_order, region_id, market_id, terminal_id, product_id, count_of_product, price_of_one_piece, order_date, client_id, comment FROM sales__05);
INSERT INTO sales__10(id, order_number, line_number_in_order, region_id, market_id, terminal_id, product_id, count_of_product, price_of_one_piece, order_date, client_id, comment) (SELECT id+5000000, order_number+500000, line_number_in_order, region_id, market_id, terminal_id, product_id, count_of_product, price_of_one_piece, order_date, client_id, comment FROM sales__05);

INSERT INTO order_numbers_dictionary__20(order_number, region_id, market_id, terminal_id, terminal_basket_number, basket_price, order_time, order_date, comment) (SELECT order_number, region_id, market_id, terminal_id, terminal_basket_number, basket_price, order_time, order_date, comment FROM order_numbers_dictionary__10);
INSERT INTO order_numbers_dictionary__20(order_number, region_id, market_id, terminal_id, terminal_basket_number, basket_price, order_time, order_date, comment) (SELECT order_number+1000000, region_id, market_id, terminal_id, terminal_basket_number, basket_price, order_time, order_date, comment FROM order_numbers_dictionary__10);
INSERT INTO sales__20(id, order_number, line_number_in_order, region_id, market_id, terminal_id, product_id, count_of_product, price_of_one_piece, order_date, client_id, comment) (SELECT id, order_number, line_number_in_order, region_id, market_id, terminal_id, product_id, count_of_product, price_of_one_piece, order_date, client_id, comment FROM sales__10);
INSERT INTO sales__20(id, order_number, line_number_in_order, region_id, market_id, terminal_id, product_id, count_of_product, price_of_one_piece, order_date, client_id, comment) (SELECT id+10000000, order_number+1000000, line_number_in_order, region_id, market_id, terminal_id, product_id, count_of_product, price_of_one_piece, order_date, client_id, comment FROM sales__10);

INSERT INTO order_numbers_dictionary__30(order_number, region_id, market_id, terminal_id, terminal_basket_number, basket_price, order_time, order_date, comment) (SELECT order_number, region_id, market_id, terminal_id, terminal_basket_number, basket_price, order_time, order_date, comment FROM order_numbers_dictionary__10);
INSERT INTO order_numbers_dictionary__30(order_number, region_id, market_id, terminal_id, terminal_basket_number, basket_price, order_time, order_date, comment) (SELECT order_number+1000000, region_id, market_id, terminal_id, terminal_basket_number, basket_price, order_time, order_date, comment FROM order_numbers_dictionary__10);
INSERT INTO order_numbers_dictionary__30(order_number, region_id, market_id, terminal_id, terminal_basket_number, basket_price, order_time, order_date, comment) (SELECT order_number+2000000, region_id, market_id, terminal_id, terminal_basket_number, basket_price, order_time, order_date, comment FROM order_numbers_dictionary__10);
INSERT INTO sales__30(id, order_number, line_number_in_order, region_id, market_id, terminal_id, product_id, count_of_product, price_of_one_piece, order_date, client_id, comment) (SELECT id, order_number, line_number_in_order, region_id, market_id, terminal_id, product_id, count_of_product, price_of_one_piece, order_date, client_id, comment FROM sales__10);
INSERT INTO sales__30(id, order_number, line_number_in_order, region_id, market_id, terminal_id, product_id, count_of_product, price_of_one_piece, order_date, client_id, comment) (SELECT id+10000000, order_number+1000000, line_number_in_order, region_id, market_id, terminal_id, product_id, count_of_product, price_of_one_piece, order_date, client_id, comment FROM sales__10);
INSERT INTO sales__30(id, order_number, line_number_in_order, region_id, market_id, terminal_id, product_id, count_of_product, price_of_one_piece, order_date, client_id, comment) (SELECT id+20000000, order_number+1000000, line_number_in_order, region_id, market_id, terminal_id, product_id, count_of_product, price_of_one_piece, order_date, client_id, comment FROM sales__10);

INSERT INTO order_numbers_dictionary__40(order_number, region_id, market_id, terminal_id, terminal_basket_number, basket_price, order_time, order_date, comment) (SELECT order_number, region_id, market_id, terminal_id, terminal_basket_number, basket_price, order_time, order_date, comment FROM order_numbers_dictionary__20);
INSERT INTO order_numbers_dictionary__40(order_number, region_id, market_id, terminal_id, terminal_basket_number, basket_price, order_time, order_date, comment) (SELECT order_number+2000000, region_id, market_id, terminal_id, terminal_basket_number, basket_price, order_time, order_date, comment FROM order_numbers_dictionary__20);
INSERT INTO sales__40(id, order_number, line_number_in_order, region_id, market_id, terminal_id, product_id, count_of_product, price_of_one_piece, order_date, client_id, comment) (SELECT id, order_number, line_number_in_order, region_id, market_id, terminal_id, product_id, count_of_product, price_of_one_piece, order_date, client_id, comment FROM sales__20);
INSERT INTO sales__40(id, order_number, line_number_in_order, region_id, market_id, terminal_id, product_id, count_of_product, price_of_one_piece, order_date, client_id, comment) (SELECT id+20000000, order_number+2000000, line_number_in_order, region_id, market_id, terminal_id, product_id, count_of_product, price_of_one_piece, order_date, client_id, comment FROM sales__20);

