\c db_diplom

DROP INDEX index_order_date_sales;
DROP INDEX index_order_date_dictionary;

DROP INDEX index_order_date_sales__01;
DROP INDEX index_order_date_sales__02;
DROP INDEX index_order_date_sales__03;
DROP INDEX index_order_date_sales__04;
DROP INDEX index_order_date_sales__05;
DROP INDEX index_order_date_sales__06;
DROP INDEX index_order_date_sales__07;
DROP INDEX index_order_date_sales__08;
DROP INDEX index_order_date_sales__09;
DROP INDEX index_order_date_sales__10;
DROP INDEX index_order_date_sales__20;
DROP INDEX index_order_date_sales__30;
DROP INDEX index_order_date_sales__40;
DROP INDEX index_order_date_sales__50;
DROP INDEX index_order_date_sales__60;
DROP INDEX index_order_date_sales__70;
DROP INDEX index_order_date_sales__80;
DROP INDEX index_order_date_sales__90;
DROP INDEX index_order_date_sales_100;

DROP INDEX index_order_date_dictionary__01;
DROP INDEX index_order_date_dictionary__02;
DROP INDEX index_order_date_dictionary__03;
DROP INDEX index_order_date_dictionary__04;
DROP INDEX index_order_date_dictionary__05;
DROP INDEX index_order_date_dictionary__06;
DROP INDEX index_order_date_dictionary__07;
DROP INDEX index_order_date_dictionary__08;
DROP INDEX index_order_date_dictionary__09;
DROP INDEX index_order_date_dictionary__10;
DROP INDEX index_order_date_dictionary__20;
DROP INDEX index_order_date_dictionary__30;
DROP INDEX index_order_date_dictionary__40;
DROP INDEX index_order_date_dictionary__50;
DROP INDEX index_order_date_dictionary__60;
DROP INDEX index_order_date_dictionary__70;
DROP INDEX index_order_date_dictionary__80;
DROP INDEX index_order_date_dictionary__90;
DROP INDEX index_order_date_dictionary_100;